### Create User 

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "salted@email.com",
    "password": "dkwdjwkdjwkdj"
}
### Signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "salted@email.com",
    "password": "dkwdjwkdjwkdj"
}

### BAD Signin Password
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "salted@email.com",
    "password": "dkwdj"
}


### find a user with given Id
GET http://localhost:3000/auth/1

### find all users with a given email
GET http://localhost:3000/auth?email=test@example.com

### Deleting a user with given id
DELETE http://localhost:3000/auth/3

### Update a user with given id
PATCH  http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "new-email@example.com"
}

